default: &default
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

development:
  <<: *default
  bucket: drew-christmas-pictures

production:
  <<: *default
  bucket: drew-christmas-pictures

